version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./templates:/myBio/templates
      - ./static:/myBIO/static
    networks:
      - myBio-network

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/myBio/static
    depends_on:
      - web
    networks:
      - myBio-network

networks:
  app-network:
    driver: bridge